### ISSUE TITLE
Unable to Build using Python 2.7 and Unreal 4.14.3

### ISSUE THREAD

**Issue by osstony** [20tab/UnrealEnginePython#135]
Hello!

I am getting the following error when trying to build from source. The only modification I've made is to use a custom python build (which I was successfully using previously). The following is what is being output from Visual Studio (apologies for the formatting):

`C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UnrealEnginePython.cpp(140): error C2653: 'FPythonSlateCommands': is not a class or namespace name
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UnrealEnginePython.cpp(140): error C3861: 'Register': identifier not found
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UnrealEnginePython.cpp(142): error C2653: 'FPythonSlateCommands': is not a class or namespace name
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UnrealEnginePython.cpp(142): error C3861: 'ApplyPythonExtenders': identifier not found
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(4): error C2065: 'ue_PyFDelegateHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(4): error C2065: 'self': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(4): error C2182: 'ue_pyfdelegatehandle_dealloc': illegal use of type 'void'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(4): error C2448: 'ue_pyfdelegatehandle_dealloc': function-style initializer appears to be a function definition
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(12): error C2065: 'ue_PyFDelegateHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(14): warning C4312: 'type cast': conversion from 'int' to 'destructor' of greater size
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(70): error C2065: 'ue_PyFDelegateHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(70): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(70): error C2059: syntax error: ')'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(71): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(75): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(75): error C2227: left of '->dhandle' must point to class/struct/union/generic type
    C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(75): note: type is 'unknown-type'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(76): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(76): error C2227: left of '->py_callable' must point to class/struct/union/generic type
    C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(76): note: type is 'unknown-type'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(78): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(91): error C2065: 'ue_PyFDelegateHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(91): error C2065: 'py_handle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(91): error C2059: syntax error: ')'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(92): error C2065: 'py_handle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(92): error C2227: left of '->dhandle' must point to class/struct/union/generic type
    C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTicker.cpp(92): note: type is 'unknown-type'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(3): error C2065: 'ue_PyFTimerHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(3): error C2065: 'self': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(3): error C2065: 'args': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(3): error C2275: 'PyObject': illegal use of this type as an expression
    C:\unreal-project\plugins\unrealenginepython\python27\include\object.h(108): note: see declaration of 'PyObject'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(3): error C2448: 'py_ue_ftimerhandle_clear': function-style initializer appears to be a function definition
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(9): error C2065: 'ue_PyFTimerHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(9): error C2065: 'self': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(9): error C2065: 'args': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(9): error C2275: 'PyObject': illegal use of this type as an expression
    C:\unreal-project\plugins\unrealenginepython\python27\include\object.h(108): note: see declaration of 'PyObject'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(9): error C2448: 'py_ue_ftimerhandle_pause': function-style initializer appears to be a function definition
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(15): error C2065: 'ue_PyFTimerHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(15): error C2065: 'self': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(15): error C2065: 'args': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(15): error C2275: 'PyObject': illegal use of this type as an expression
    C:\unreal-project\plugins\unrealenginepython\python27\include\object.h(108): note: see declaration of 'PyObject'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(15): error C2448: 'py_ue_ftimerhandle_unpause': function-style initializer appears to be a function definition
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(33): error C2065: 'ue_PyFTimerHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(33): error C2065: 'self': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(33): error C2182: 'ue_pyftimerhandle_dealloc': illegal use of type 'void'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(33): error C2448: 'ue_pyftimerhandle_dealloc': function-style initializer appears to be a function definition
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(41): error C2065: 'ue_PyFTimerHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(43): warning C4312: 'type cast': conversion from 'int' to 'destructor' of greater size
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(114): error C2065: 'ue_PyFTimerHandle': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(114): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(114): error C2059: syntax error: ')'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(115): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(119): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(119): error C2227: left of '->thandle' must point to class/struct/union/generic type
    C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(119): note: type is 'unknown-type'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(120): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(120): error C2227: left of '->py_callable' must point to class/struct/union/generic type
    C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(120): note: type is 'unknown-type'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(122): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(122): error C2227: left of '->py_callable' must point to class/struct/union/generic type
    C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(122): note: type is 'unknown-type'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(122): error C2227: left of '->ob_refcnt' must point to class/struct/union/generic type
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(123): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(123): error C2227: left of '->world' must point to class/struct/union/generic type
    C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(123): note: type is 'unknown-type'
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyTimer.cpp(125): error C2065: 'ret': undeclared identifier
C:\unreal-project\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UEPyWorld.cpp(147): error C2065: 'ue_PyUObjectType': undeclared identifier`

**Comment by rdeioris** [comment]
This is really strange, can you regenerate the visual studio files from the uproject file ?  Which options are you using for the custom built python ?

**Comment by osstony** [comment]
I've tried regenerating and it doesn't seem to solve it. The python I'm using is just a 2.7 build that's built using Visual Studio 2015. It's the same python build that I've been using the whole time since starting to help with this project last year. I haven't built this project in a couple of months, just getting back to it now. 

The errors don't seem to indicate anything to do with python and if I add additional #includes in a few places it seems to resolve some of them but if you are able to build then I would like to track down what's wrong in my environment that is causing these errors.

**Comment by osstony** [comment]
It seems the issue was due to some files being set to Read-Only and others not. This caused the Unreal build tool to disregard some files when doing it's Adaptive unity file thing. 

Sorry for the extra noise!
