### ISSUE TITLE
Will you build this for windows UE 4.25.3?

### ISSUE THREAD

**Issue by shdwdln** [20tab/UnrealEnginePython#860]
I am trying to build this and I keep getting errors in VS2019 like:
1>C:\Program Files\Epic Games\UE_4.25\Engine\Source\Runtime\CoreUObject\Public\UObject/Script.h(372): error C2079: 'FScriptInstrumentationSignal' uses undefined struct 'COREUOBJECT_API'

But all the include dirs are there so Im not sure why it can't find that struct.

Could you compile a build with 2.7?

**Comment by shdwdln** [comment]
Nevermind. I got it built on a separate install on my laptop. The current test bed I was using was with VS2017 and VS2019 installed and seemed to have some iissues with VS2019.
