### ISSUE TITLE
Error with module h5py

### ISSUE THREAD

**Issue by yobiminds** [20tab/UnrealEnginePython#651]
With UE4.21(Win10), I installed via 
`python -m pip install -t . <package>`
two packages, matplotlib and **h5py**. Both installations were succesfull, and matplotlib works fine, while h5py gave me some problem. Here are some detail:

- running a python.exe console from plugin (outside UE4, within a windows CMD console), "import h5py" works.
- from UE4 Python Console, "import h5py" gives this error:
`>>> import h5py`
`DLL load failed: The specified procedure could not be found.`
`Traceback (most recent call last):`
 `File "<string>", line 1, in <module>`
  `File "D:\work_in_progress\UE4\erroreh5py\Plugins\UnrealEnginePython\Binaries\Win6\h5py\__init__.py", line 36, in <module>`
  `from ._conv import register_converters as _register_converters`
  `File "h5py\h5r.pxd", line 21, in init h5py._conv`
  `File "h5py\_objects.pxd", line 12, in init h5py.h5r`
  `File "h5py\_objects.pyx", line 1, in init h5py._objects`
`ImportError: DLL load failed: The specified procedure could not be found.`

- runnig the game, at the event BeginPLay I get
`LogPython: Error: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'`
`LogPython: Error: Traceback (most recent call last):`
`LogPython: Error:   File "<string>", line 1, in <module>`
`LogPython: Error:   File "D:\work_in_progress\UE4\erroreh5py\Plugins\UnrealEnginePython\Binaries\Win64\h5py\__init__.py", line 36, in <module>`
    `from ._conv import register_converters as _register_converters`
`LogPython: Error:   File "h5py\h5r.pxd", line 21, in init h5py._conv`
`LogPython: Error:   File "h5py\h5r.pyx", line 145, in init h5py.h5r`
`LogPython: Error: AttributeError: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'`

I tried with UE 4.20, with/without matplotlib installed, no luck until now.
Any suggestion?
Thank you,
Roberto

**Comment by yobiminds** [comment]
Quick update, even using system installation of python, the issue remains.

**Comment by yobiminds** [comment]
Hoping to be of some help, I can tell you that in UE 4.20.3 it works downgrading the h5py version to 2.7.0, 
Will test more when binaries of Python Plugin will be available for UE 4.21.2

**Comment by yobiminds** [comment]
h5py version to 2.7.0, works fine on UE 4.21.2
